hook_add = '''

" remember position
" autocmd MyAutoCmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif



" Reload .vimrc automatically.
"autocmd MyAutoCmd BufWritePost .vimrc,vimrc,*.rc.vim,*.toml source $MYVIMRC | redraw

" Auto reload VimScript.
"autocmd MyAutoCmd BufWritePost,FileWritePost *.vim nested
"\ if &l:autoread > 0 | source <afile> |
"\   echo 'source ' . bufname('%') |
"\ endif


'''

[ftplugin]
man = '''
set mouse=a
"highlight default link manBold manUnderline
"highlight default link manItalic manUnderline
"highlight! default link manSubheading Conditional
'''

qf = '''
setlocal nofoldenable
'''

toml = 'syntax sync minlines=500'

help = '''
setlocal iskeyword+=:
setlocal iskeyword+=#
setlocal iskeyword+=-
map q :close<CR>
'''

